# Generated by Django 3.1.2 on 2024-01-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_userdetail_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
